# Generated by Django 3.1.13 on 2021-09-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
