# Generated by Django 3.1.13 on 2021-09-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycontact', '0002_auto_20210901_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Contacts',
        ),
    ]
